# Generated by Django 3.2.4 on 2021-07-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('priceBuy', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('cusContact', models.CharField(max_length=20, null=True)),
                ('cusAddress', models.CharField(max_length=200, null=True)),
                ('cusEmail', models.EmailField(max_length=254, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField()),
                ('price_buy', models.IntegerField(null=True)),
                ('price_sell', models.IntegerField(null=True)),
                ('price_total', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
                ('sell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.sell')),
            ],
        ),
    ]
